### ISSUE TITLE
Jruby Support

### ISSUE THREAD

**Issue by dometto** [sinatra/mustermann#72]
The docs state that `jruby` is currently not supported, but I can `gem install mustermann` just fine. Is it ready for use with `jruby` after all?

I have tried to run the specs on `jruby`, but this fails because the `redcarpet` gem required by `support` is not compatible (it relies on `posix-spawn`). If I disable the `redcarpet` dependency in the gemspec, the specs run but result in 23 failures. I take it that is not related to removing`redcarpet` (since else I should be seeing errors concerning that)?

If not that, can you indicate what needs to happen to fully support `jruby`? I would be interested in getting that running so when can upgrade https://github.com/gollum/gollum to `sinatra v2`.

**Comment by zzak** [comment]
Hi @dometto,

I'm not sure why it's not supported to be honest, but your experience leads me to believe that it isn't.

As far as adding support, I'd need a patch to get it building under CI.

Is this something you'd be interested in working on?

**Comment by epergo** [comment]
> I have tried to run the specs on jruby, but this fails because the redcarpet gem required by support is not compatible (it relies on posix-spawn). If I disable the redcarpet dependency in the gemspec, the specs run but result in 23 failures. I take it that is not related to removingredcarpet (since else I should be seeing errors concerning that)?

Is it redcarpet even used at all? I fail to find _where_ is being used

**Comment by dentarg** [comment]
Looks like there's a bunch of things to investigate for JRuby support: https://github.com/sinatra/mustermann/runs/7393804603?check_suite_focus=true#step:4:1

**Comment by headius** [comment]
The jobs referenced are old enough that the logs are gone, but running rspec locally yields only two failures (running against jruby/jruby#8922):

```
  1) Mustermann new string argument is expected to raise ArgumentError with "unsupported type :ast (cannot load such file -- mustermann/ast)"
     Failure/Error: example { expect { Mustermann.new('', type: :ast) }.to raise_error(ArgumentError, "unsupported type :ast (cannot load such file -- mustermann/ast)") }
     
       expected ArgumentError with "unsupported type :ast (cannot load such file -- mustermann/ast)", got #<ArgumentError: unsupported type :ast (no such file to load -- mustermann/ast)> with backtrace:
         # ./mustermann/lib/mustermann.rb:94:in 'block in []'
         # ./mustermann/lib/mustermann.rb:94:in 'block in []'
         # ./mustermann/lib/mustermann.rb:92:in 'block in []'
         # ./mustermann/lib/mustermann.rb:91:in '[]'
         # ./mustermann/lib/mustermann.rb:68:in 'new'
         # ./mustermann/spec/mustermann_spec.rb:18:in 'block in <main>'
         # ./mustermann/spec/mustermann_spec.rb:18:in 'block in <main>'
     # ./mustermann/spec/mustermann_spec.rb:18:in 'block in <main>'

  2) Mustermann [] is expected to raise ArgumentError with "unsupported type :ast (cannot load such file -- mustermann/ast)"
     Failure/Error: example { expect { Mustermann[:ast]      }.to raise_error(ArgumentError, "unsupported type :ast (cannot load such file -- mustermann/ast)") }
     
       expected ArgumentError with "unsupported type :ast (cannot load such file -- mustermann/ast)", got #<ArgumentError: unsupported type :ast (no such file to load -- mustermann/ast)> with backtrace:
         # ./mustermann/lib/mustermann.rb:94:in 'block in []'
         # ./mustermann/lib/mustermann.rb:94:in 'block in []'
         # ./mustermann/lib/mustermann.rb:92:in 'block in []'
         # ./mustermann/lib/mustermann.rb:91:in '[]'
         # ./mustermann/spec/mustermann_spec.rb:65:in 'block in <main>'
         # ./mustermann/spec/mustermann_spec.rb:65:in 'block in <main>'
     # ./mustermann/spec/mustermann_spec.rb:65:in 'block in <main>'
```

I am not familiar enough with mustermann to know what this error means, but I believe we can get JRuby fully green. I've started such a PR in https://github.com/sinatra/mustermann/pull/145.

**Comment by headius** [comment]
All fixes have been merged and the latest jruby-head builds should be green once #145 picks it up and merges. This can be resolved at that point.
